In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import time

from optimizer import *
from LookAhead import LookAheadOpt

In [2]:
def quad_10(x):
    return np.sum(x**2)

def rosen(x, a=1, b=5):
    n = len(x)
    return np.sum((a - x[:-1])**2 + b*(x[1:]- x[:-1]**2)**2)

In [3]:
def process(opt, func, x, k=2000):
    p = np.zeros((k+1, 10))
    p[0] = x
    
    for i in range(k):
        x = opt.step(func, x)
        p[i+1] = x
    
    return p

def evaluate(optimizer, func, num_x, N=100, tol=1e-10):
    data = {'abs_err':np.zeros(N), 'abs_err_func':np.zeros(N),
           'num_func_eval': np.zeros(N), 'time':np.zeros(N)}
    
    for i in range(N):
        
        x = np.zeros(num_x)
        for k in range(num_x):
            sign = np.random.choice([1, -1])
            y = np.random.random() * 4 - 2
            x[k] = sign * np.exp(y)
        
        diff = np.Inf
        diffval = np.Inf
        n = 0
        t = 0
        
        while diffval > tol:
            tict = time.time()
            nx = optimizer.step(func, x)
            elapsed_time = time.time() - tict
            diff = np.linalg.norm(nx-x)
            diffval = np.abs(func(nx)-func(x))
            n += 1
            t += elapsed_time
            
            x = nx
            print(x)
        data['abs_err'][i] = diff
        data['abs_err_func'][i] = diffval
        data['num_func_eval'][i] = n
        data['time'][i] = t
        
    
    return data

In [4]:
def h(x):
    return np.array([np.sum(x) - 2])

In [5]:
adam = AdamOpt(10)
momentum = MomemtunOpt(10)
lagrange = ArgumentedLagrange(h, 1)

lookahead_adam = LookAheadOpt(adam)
lookahead_mom = LookAheadOpt(momentum)
lookahead_lag = LookAheadOpt(lagrange)

In [6]:
evaluate(lagrange, rosen, 10, N=1)

[ 0.87574705  0.81205771  0.72805109  0.61117346  0.46126989  0.3036976
  0.18370667  0.12113899  0.07869295 -0.09769866]
[ 0.38841084  0.18311325  0.07790553  0.05310147  0.05016298  0.04988084
  0.04976208  0.04871185  0.03679278 -0.14602215]
[ 0.76139581  0.62280771  0.45290174  0.28121137  0.1602749   0.10861303
  0.0945575   0.08827049  0.06621092 -0.10894591]
[ 0.62944824  0.4362434   0.24969762  0.13011973  0.08731937  0.07848435
  0.07674571  0.07402251  0.05586884 -0.12140261]
[ 0.71188576  0.54879573  0.36424558  0.20592437  0.11981282  0.09287006
  0.08687025  0.08273255  0.06230502 -0.1135627 ]
[ 0.67010044  0.49008124  0.30145692  0.16146514  0.10000922  0.08466794
  0.08154742  0.07828229  0.05903853 -0.11750955]
[ 0.6941725   0.52349097  0.33636718  0.18529538  0.11029752  0.08906061
  0.08454259  0.08083269  0.06091967 -0.11522734]
[ 0.68119261  0.50533674  0.31712875  0.17188944  0.10442409  0.08659973
  0.08290675  0.07945323  0.05990346 -0.1164583 ]
[ 0.68845     0.5

{'abs_err': array([0.]),
 'abs_err_func': array([0.]),
 'num_func_eval': array([23.]),
 'time': array([2.63235188])}

In [ ]:
num_x = 10
x = np.zeros(num_x)
for k in range(num_x):
    sign = np.random.choice([1, -1])
    y = np.random.random() * 4 - 2
    x[k] = sign * np.exp(y)

In [13]:
lam = np.ones(4)
k = np.ones(4)

In [15]:
np.matmul(lam, 2*k)

8.0

In [8]:
from methods import gradient

In [35]:
def f(x):
    return x[0]**2 - x[1]*x[0]

In [38]:
def gradient(f, x, h=1e-10):
    '''
    Calculate the gradient of f at x by using forward difference

    Args:
        f: function that want to find the gradient
        x: the position where want to find the gradient

    Returns:
        grad: an array of gradients for each dimension
    '''
    temp = []
    N = len(x)

    for i in range(N):
        xx = np.copy(x)
        
        xx[i] += h
        print(xx)
        print((f(xx) - f(x)) / h)
        temp.append((f(xx) - f(x)) / h)

    return np.array(temp)

In [39]:
gradient(f, [1.0,1.0])

[1. 1.]
1.000000082740371
[1. 1.]
-1.000000082740371


array([ 1.00000008, -1.00000008])

In [21]:
def f(x):
    return x[0]**2

In [22]:
gradient(f, [1])

array([0.])

In [32]:
np.zeros(4)

array([0., 0., 0., 0.])